name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Get variables
        id: get_vars
        run: |
          echo '::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)'
          echo '::set-output name=DATE::$(date +'%D')'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Bump package version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm version ${{ github.ref_name }} --git-tag-version false

      - name: Run build
        run: pnpm build

      - name: Update repository
        run: |
          git add .
          git commit -am '${{ github.ref_name }}'
          git push

      # fetches the new files from the locale-repo (has to be public)
      - name: Update locale files
        uses: Maximus7474/locale-manager-action@v1.0.0
        with:
          resource-name: 'mps-fleecanow'
          locale-repo: 'Maximus7474/mps-locales'
          locale-directory: './locales'

      # an ugly step to check if any changes occured to the locale directory
      # this is an example, you can rename directories
      - name: Check if locales were updated
        id: git-check
        run: |
          # Check for changes only in the locales directory
          git_status=$(git status --porcelain ./locales)
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$git_status" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # (optionnal) update your repository with the new changes
      # it is neater so do it and don't consider it as optional
      - name: Commit and Push if changes were made to locales
        if: steps.git-check.outputs.changes != ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am 'chore(locales): updated for ${{ github.ref_name }}'
          git push

      - name: Bundle release files
        run: |
          zip -r ${{ github.event.repository.name }}.zip . -x "./.*" "./node_modules/*" "./scripts/*" "./src/*" "./web/*" "./tsconfig.json" "./biome.json" "./pnpm-lock.yaml" "./package.json" "./eslint.config.js" "./designs/*"

      - name: Bundle source files
        run: |
          zip -r ${{ github.event.repository.name }}-source.zip . -x "./node_modules/*" "./pnpm-lock.yaml" "./designs/*" "./.github/*" "./.git/*" "*.zip"

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: '${{ env.RELEASE_VERSION }}'
          prerelease: false
          files: |
            ${{ github.event.repository.name }}.zip
            ${{ github.event.repository.name }}-source.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
